export const LOCATION = [
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "25",
    backDoor: false,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "25",
    backDoor: false,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "2",
    weight: "630",
    lamp: "Led matrix",
    floors: "10(-2 - 8)",
    backDoor: true,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "3",
    weight: "630",
    lamp: "Led matrix",
    floors: "10(-2 - 8)",
    backDoor: true,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "4",
    weight: "630",
    lamp: "Long",
    floors: "10(-2 - 8)",
    backDoor: true,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "5",
    weight: "630",
    lamp: "Long",
    floors: "12",
    backDoor: false,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Cargo",
    section: "5",
    weight: "1000",
    lamp: "Led matrix!!! Long",
    floors: "12",
    backDoor: false,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Passenger",
    section: "6",
    weight: "630",
    lamp: "Long",
    floors: "12",
    backDoor: false,
  },
  {
    id: "7g",
    name: 'ЖК "МАЛАХИТ", 7Г',
    address: "ул.Богдановская, 7Г",
    type: "Cargo",
    section: "6",
    weight: "1000",
    lamp: "Long",
    floors: "12",
    backDoor: true,
  },
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "25",
    backDoor: false,
  },
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "25",
    backDoor: false,
  },
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "25",
    backDoor: false,
  },
  {
    id: "e",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Е",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "g",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Г",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "d",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Д",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "z",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "З",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "k",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "К",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
  },
  {
    id: "l",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "Л",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
  },
  {
    id: "m",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "М",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
  },
  {
    id: "n",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "Н",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
  },
  {
    id: "tg",
    name: 'ЖК "Тихая Гавань"',
    address: "ул. Набережно-Корчеватская, 29",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "8",
    backDoor: false,
  },
  {
    id: "sk",
    name: 'СК "ВЕЛТЛИНЕР"',
    address: "ул. Новоконстантиновская, 1Г",
    type: "Passenger",
    section: "1",
    weight: "450",
    lamp: "Long",
    floors: "4",
    backDoor: false,
  },
  {
    id: "sund",
    name: '"СУНДУК"',
    address: "ул. Константиновская, 71",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "4",
    backDoor: false,
  },
  {
    id: "podol",
    name: 'БЦ "ПОДОЛ"',
    address: "ул. Нижнеюрковская, 9",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
  },
  {
    id: "pz",
    name: "Дженбюри",
    address: "ул. Степанченко, 17А",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "2",
    backDoor: true,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Cargo",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
  },
];
