export const LOCATION = [
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "25",
    backDoor: false,
    model: "OTIS Gen2",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "25",
    backDoor: false,
    model: "OTIS Gen2",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "7d",
    name: 'ЖК "МАЛАХИТ", 7Д',
    address: "ул. Богдановская, 7Д",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "25",
    backDoor: false,
    model: "OTIS Gen2",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "e",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Е",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "g",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Г",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "d",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "Д",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "z",
    name: 'ЖК "Эмоция"',
    address: "с.Хотов,Промышленная,1Г-З",
    type: "Passenger",
    section: "З",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "k",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "К",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
    model: "MIZUI Monarch NICE3000new",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "l",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "Л",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
    model: "MIZUI Monarch NICE3000new",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "m",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "М",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
    model: "MIZUI Monarch NICE3000new",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "n",
    name: 'ЖК "Люмва"',
    address: "с.Хотов, ул. Промышленная, 1К-Н",
    type: "Passenger",
    section: "Н",
    weight: "630",
    lamp: "Long",
    floors: "7",
    backDoor: true,
    model: "MIZUI Monarch NICE3000new",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "tg",
    name: 'ЖК "Тихая Гавань"',
    address: "ул. Набережно-Корчеватская, 29",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "8",
    backDoor: false,
    model: "MITSUBISHI ELEVATORS",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "sk",
    name: 'СК "ВЕЛТЛИНЕР"',
    address: "ул. Новоконстантиновская, 1Г",
    type: "Passenger",
    section: "1",
    weight: "450",
    lamp: "Long",
    floors: "4",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "sund",
    name: '"СУНДУК"',
    address: "ул. Константиновская, 71",
    type: "Passenger",
    section: "1",
    weight: "630",
    lamp: "Long",
    floors: "4",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "podol",
    name: 'БЦ "ПОДОЛ"',
    address: "ул. Нижнеюрковская, 9",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
    model: "MIZUI Monarch NICE3000new",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "pz",
    name: "Дженбюри",
    address: "ул. Степанченко, 17А",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "2",
    backDoor: true,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "7",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Cargo",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
  {
    id: "dk",
    name: "ДИЛОР КОНСАЛТИНГ",
    address: "пр-т. Победы, 53",
    type: "Passenger",
    section: "2",
    weight: "1000",
    lamp: "Long",
    floors: "8",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Вячеслав",
    mechanicPhone: "+380638167171",
    isFault: false,
  },
];
export const LOCATIONDEN = [
  {
    id: "3t",
    name: "Трутенко, 3",
    address: "ул. Трутенко, 3",
    type: "Cargo",
    section: "1",
    weight: "1000",
    lamp: "Long",
    floors: "25",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "4g",
    name: 'ЖК "МИЛЛЕНИУМ"',
    address: "ул.Кожедуба, 3",
    type: "Passenger",
    section: "4g",
    weight: "400",
    lamp: "short",
    floors: "11",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "4d",
    name: 'ЖК "МИЛЛЕНИУМ"',
    address: "ул.Кожедуба, 3",
    type: "Cargo",
    section: "4d",
    weight: "1000",
    lamp: "Long",
    floors: "11",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "3a",
    name: 'ЖК "МИЛЛЕНИУМ"',
    address: "ул.Кожедуба, 3",
    type: "Passenger",
    section: "3a",
    weight: "400",
    lamp: "short",
    floors: "10",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "3a",
    name: 'ЖК "МИЛЛЕНИУМ"',
    address: "ул.Кожедуба, 3",
    type: "Cargo",
    section: "3a",
    weight: "1000",
    lamp: "Short",
    floors: "10",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "3б",
    name: 'ЖК "МИЛЛЕНИУМ"',
    address: "ул.Кожедуба, 3",
    type: "Passenger",
    section: "3б",
    weight: "400",
    lamp: "Short",
    floors: "10",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
  {
    id: "3б",
    name: 'ЖК ""',
    address: "ул.Кожедуба, 3",
    type: "Passenger",
    section: "3б",
    weight: "400",
    lamp: "Short",
    floors: "10",
    backDoor: false,
    model: "MIZUI Step",
    mechanic: "Хоменко Денис",
    mechanicPhone: "+380668809136",
    isFault: false,
  },
];
